### PR TITLE
Fix dependencies

### PR DESCRIPTION
**Pull request by JerrickRowe**
The dependency on empy is broken. Resolve it by freezing the version of empy to 3.3.4. Other dependencies are also frozen at their current versions.
Some refinements to testing scripts have been made for better environmental compatibility.

### CODE REVIEW

**Comment by Valle125** [comment]
@JerrickRowe Thank you very much, this saved my day!
Freezing the version of empy to 3.3.4 fixes the following error, when trying to compile dsdl messages
```
Caught exception! 'dict' object has no attribute 'unknownScriptName'
```

**Comment by dslc** [comment]
Thanks for this suggestion.
Compilation seems to be completely broken with the latest version of the `empy` package.
Downgrading resolved the issue.

**Comment by tridge** [comment]
this conflicts with the existing change to empy version

**Comment by JerrickRowe** [comment]
This PR is too old to be merged

**Pull request closed without merging**
